# Generated by Django 3.1.7 on 2021-04-07 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='Address',
            field=models.TextField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='country',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='gender',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employees',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.group'),
        ),
    ]
