# Generated by Django 3.1.7 on 2021-04-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210407_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='branch',
            new_name='Group',
        ),
    ]
