# Generated by Django 3.1.7 on 2021-04-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210408_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Group',
            new_name='Branch',
        ),
    ]
