# Generated by Django 3.2.9 on 2021-11-30 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('user', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=False)),
            ],
            options={
                'verbose_name_plural': 'comment',
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_id', models.CharField(max_length=10)),
                ('comment_user', models.CharField(max_length=100)),
                ('user_comments', models.TextField()),
                ('comment_date', models.DateTimeField()),
                ('comment_likes', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='editpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=250)),
                ('page_content', models.TextField()),
                ('mtitle', models.TextField()),
                ('mkeywords', models.TextField()),
                ('mdescription', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'joinus',
            },
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('profile_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'photos',
            },
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=60)),
                ('Lname', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('Fax', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('Status', models.SmallIntegerField(default=0)),
                ('created_date', models.DateTimeField()),
                ('last_login', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'register',
            },
        ),
        migrations.CreateModel(
            name='testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('placed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'testimonials',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_surname', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_status', models.IntegerField()),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('visit', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'views',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gb', models.ImageField(blank=True, null=True, upload_to='')),
                ('quotation', models.TextField()),
                ('arrival_date', models.CharField(max_length=100)),
                ('departure_date', models.CharField(max_length=100)),
                ('cause_death', models.TextField()),
                ('place_death', models.CharField(max_length=250)),
                ('other', models.TextField()),
                ('rest_place', models.CharField(max_length=200)),
                ('other_names', models.TextField()),
                ('ethnicity', models.CharField(max_length=200)),
                ('alma', models.TextField()),
                ('political', models.TextField()),
                ('religion', models.CharField(max_length=200)),
                ('spouse', models.CharField(max_length=200)),
                ('children', models.TextField()),
                ('parents', models.TextField()),
                ('known', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profile',
            },
        ),
    ]
