# Generated by Django 3.1.7 on 2021-04-05 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=19, null=True)),
                ('mobile', models.CharField(max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('address', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=7)),
                ('country', models.CharField(choices=[('AUSTRALIA', 'AUSTRALIA'), ('BANGLADESH', 'BANGLADESH'), ('CHINA', 'CHINA'), ('DENMARK', 'DENMARK'), ('EGYPT', 'EGYPT'), ('INDIA', 'INDIA'), ('SWEDEN', 'SWEDEN'), ('USA', 'USA')], max_length=15)),
                ('marks_percentage', models.FloatField()),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
