# Generated by Django 3.1.7 on 2021-04-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='group',
            field=models.CharField(choices=[('CIVIL', 'CIVIL'), ('MECH', 'MECH'), ('EEE', 'EEE'), ('CSC', 'CSC')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
